services:
  mongo:
    container_name: mongoGitEdu
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/src/db
    restart: unless-stopped

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
    depends_on:
      - mongo
    restart: unless-stopped


volumes:
  mongo_data: